# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "ivylorin"
subtitle: "ivylorin"
author:  "olivia"
header:
 title:
 subtitle: "click a pic to see a full version!"
footer:
 name: "ivylorin (olivia)"
 bio: "I'm a 17 year old artist from Poland. I do digital art, as well as traditional and I especially enjoy drawing portraits, fanarts and cartoony characters. My cartoon-like style is full of saturated, vibrant colors and big contrasts. Other than art, I'm really into dramas, video games and internet mysteries. If you'd like to contact me, dm me on my twitter (linked down below).  "
social_urls:
  twitter: "https://twitter.com/ivylorinx"
